# Code generated by kreuzberg-e2e-generator. DO NOT EDIT.
# To regenerate: cargo run -p kreuzberg-e2e-generator -- generate --lang r
#
# Tests for structured fixtures.
# nolint start

test_that("structured_csv_basic", {
  result <- run_fixture(
    "structured_csv_basic",
    "csv/stanley_cups.csv",
    NULL,
    requirements = character(0),
    notes = NULL,
    skip_if_missing = TRUE
  )
  assert_expected_mime(result, c("text/csv"))
  assert_min_content_length(result, 20L)
})

test_that("structured_json_basic", {
  result <- run_fixture(
    "structured_json_basic",
    "json/sample_document.json",
    NULL,
    requirements = character(0),
    notes = NULL,
    skip_if_missing = TRUE
  )
  assert_expected_mime(result, c("application/json"))
  assert_min_content_length(result, 20L)
  assert_content_contains_any(result, c("Sample Document", "Test Author"))
})

test_that("structured_json_simple", {
  result <- run_fixture(
    "structured_json_simple",
    "json/simple.json",
    NULL,
    requirements = character(0),
    notes = NULL,
    skip_if_missing = TRUE
  )
  assert_expected_mime(result, c("application/json"))
  assert_min_content_length(result, 10L)
  assert_content_contains_any(result, c("{", "name"))
})

test_that("structured_toml_basic", {
  result <- run_fixture(
    "structured_toml_basic",
    "data_formats/cargo.toml",
    NULL,
    requirements = character(0),
    notes = NULL,
    skip_if_missing = TRUE
  )
  assert_expected_mime(result, c("application/toml", "text/toml"))
  assert_min_content_length(result, 10L)
})

test_that("structured_yaml_basic", {
  result <- run_fixture(
    "structured_yaml_basic",
    "yaml/simple.yaml",
    NULL,
    requirements = character(0),
    notes = NULL,
    skip_if_missing = TRUE
  )
  assert_expected_mime(result, c("application/yaml", "text/yaml", "text/x-yaml", "application/x-yaml"))
  assert_min_content_length(result, 10L)
})

test_that("structured_yaml_simple", {
  result <- run_fixture(
    "structured_yaml_simple",
    "yaml/simple.yaml",
    NULL,
    requirements = character(0),
    notes = NULL,
    skip_if_missing = TRUE
  )
  assert_expected_mime(result, c("application/x-yaml"))
  assert_min_content_length(result, 10L)
})
# nolint end
