# Code generated by kreuzberg-e2e-generator. DO NOT EDIT.
# To regenerate: cargo run -p kreuzberg-e2e-generator -- generate --lang r
#
# Tests for image fixtures.
# nolint start

test_that("image_metadata_only", {
  result <- run_fixture(
    "image_metadata_only",
    "images/example.jpg",
    list(ocr = NULL),
    requirements = character(0),
    notes = NULL,
    skip_if_missing = TRUE
  )
  assert_expected_mime(result, c("image/jpeg"))
  assert_max_content_length(result, 100L)
})

test_that("image_svg_basic", {
  result <- run_fixture(
    "image_svg_basic",
    "xml/simple_svg.svg",
    NULL,
    requirements = character(0),
    notes = NULL,
    skip_if_missing = TRUE
  )
  assert_expected_mime(result, c("image/svg+xml"))
  assert_min_content_length(result, 5L)
})
# nolint end
