name: Install WASI SDK
description: |
  Install WASI SDK for cross-compiling C/C++ libraries (Tesseract, Leptonica) to WebAssembly.
  Thin wrapper around bytecodealliance/setup-wasi-sdk-action.

inputs:
  version:
    description: WASI SDK version to install
    required: false
    default: '25'

runs:
  using: composite
  steps:
    - name: Install WASI SDK
      uses: bytecodealliance/setup-wasi-sdk-action@dcd040abc428fe35253676ef0e6379fba9bf8f9f # main
      with:
        version: ${{ inputs.version }}
        github-token: ${{ github.token }}

    - name: Verify WASI SDK
      shell: bash
      run: |
        echo "WASI SDK installed at: $WASI_SDK_PATH"
        ls "$WASI_SDK_PATH" || true
