name: Setup OpenSSL
description: Install and expose OpenSSL headers/libs across platforms
runs:
  using: composite
  steps:
    - name: Restore OpenSSL cache (Linux)
      if: runner.os == 'Linux'
      uses: actions/cache@v5
      id: cache-linux
      with:
        path: |
          /home/runner/.cache/openssl-build
        key: openssl-${{ runner.os }}-${{ hashFiles('/usr/bin/pkg-config', '/usr/bin/gcc') }}-v2
        restore-keys: |
          openssl-${{ runner.os }}-

    - name: Install OpenSSL (Linux)
      if: runner.os == 'Linux' && steps.cache-linux.outputs.cache-hit != 'true'
      shell: bash
      run: |
        set -euo pipefail
        sudo apt-get update
        sudo apt-get install -y pkg-config libssl-dev build-essential

    - name: Configure OpenSSL environment (Linux)
      if: runner.os == 'Linux'
      shell: bash
      run: |
        set -euo pipefail
        # Set environment variables for OpenSSL detection
        # On Ubuntu, OpenSSL is typically in /usr with pkgconfig in arch-specific path
        OPENSSL_ROOT="/usr"
        PKG_CONFIG_DIR="/usr/lib/x86_64-linux-gnu/pkgconfig"

        # Verify OpenSSL installation
        if [ ! -f "${PKG_CONFIG_DIR}/openssl.pc" ]; then
          echo "ERROR: openssl.pc not found at ${PKG_CONFIG_DIR}" >&2
          echo "Searching for openssl.pc..." >&2
          find /usr -name "openssl.pc" 2>/dev/null || true
          exit 1
        fi

        # Export environment variables
        {
          echo "OPENSSL_DIR=${OPENSSL_ROOT}"
          echo "OPENSSL_LIB_DIR=/usr/lib/x86_64-linux-gnu"
          echo "OPENSSL_INCLUDE_DIR=/usr/include"
          echo "PKG_CONFIG_PATH=${PKG_CONFIG_DIR}:${PKG_CONFIG_PATH:-}"
        } >> "$GITHUB_ENV"

        echo "OpenSSL configuration completed:"
        echo "  OPENSSL_DIR=${OPENSSL_ROOT}"
        echo "  PKG_CONFIG_PATH=${PKG_CONFIG_DIR}"
        pkg-config --modversion openssl

    - name: Restore OpenSSL cache (macOS)
      if: runner.os == 'macOS'
      uses: actions/cache@v5
      id: cache-macos
      with:
        path: /usr/local/opt/openssl@3/
        key: openssl-${{ runner.os }}-${{ hashFiles('/usr/bin/gcc') }}-v2
        restore-keys: |
          openssl-${{ runner.os }}-

    - name: Install OpenSSL (macOS)
      if: runner.os == 'macOS' && steps.cache-macos.outputs.cache-hit != 'true'
      shell: bash
      run: |
        set -euo pipefail
        # Install packages only if not already present
        brew list openssl@3 &>/dev/null || brew install openssl@3
        brew list pkg-config &>/dev/null || brew install pkg-config

    - name: Configure OpenSSL environment (macOS)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        set -euo pipefail
        prefix="$(brew --prefix openssl@3 2>/dev/null || brew --prefix openssl 2>/dev/null || true)"
        if [ -z "$prefix" ]; then
          echo "Failed to locate Homebrew OpenSSL prefix" >&2
          exit 1
        fi
        {
          echo "OPENSSL_DIR=$prefix"
          echo "OPENSSL_LIB_DIR=$prefix/lib"
          echo "OPENSSL_INCLUDE_DIR=$prefix/include"
          echo "PKG_CONFIG_PATH=$prefix/lib/pkgconfig:${PKG_CONFIG_PATH:-}"
        } >> "$GITHUB_ENV"

    - name: Restore OpenSSL cache (Windows)
      if: runner.os == 'Windows'
      uses: actions/cache@v5
      id: cache-windows
      with:
        path: |
          C:\vcpkg\installed\x64-windows-static-md
          C:\vcpkg\downloads
        key: openssl-${{ runner.os }}-${{ hashFiles('C:\vcpkg\vcpkg.exe') }}-v3
        restore-keys: |
          openssl-${{ runner.os }}-

    - name: Install OpenSSL (Windows)
      if: runner.os == 'Windows' && steps.cache-windows.outputs.cache-hit != 'true'
      shell: pwsh
      run: |
        $vcpkg = (Get-Command vcpkg -ErrorAction SilentlyContinue)?.Source
        if (-not $vcpkg) {
          $candidate = "C:\vcpkg\vcpkg.exe"
          if (Test-Path $candidate) {
            $vcpkg = $candidate
          }
        }

        if (-not $vcpkg) {
          Write-Error "vcpkg not found (expected in PATH or at C:\vcpkg\vcpkg.exe)"
          exit 1
        }

        & $vcpkg install openssl:x64-windows-static-md

    - name: Configure OpenSSL environment (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        $vcpkgRoot = "C:\vcpkg\installed\x64-windows-static-md"
        if (-not (Test-Path $vcpkgRoot)) {
          Write-Error "vcpkg OpenSSL installation not found at $vcpkgRoot"
          exit 1
        }

        Add-Content -Path $env:GITHUB_ENV -Value "VCPKG_ROOT=C:\vcpkg"
        Add-Content -Path $env:GITHUB_ENV -Value "OPENSSL_DIR=$vcpkgRoot"
        Add-Content -Path $env:GITHUB_ENV -Value "OPENSSL_LIB_DIR=$vcpkgRoot\lib"
        Add-Content -Path $env:GITHUB_ENV -Value "OPENSSL_INCLUDE_DIR=$vcpkgRoot\include"
        Add-Content -Path $env:GITHUB_ENV -Value "OPENSSL_STATIC=1"
