// Code generated by kreuzberg-e2e-generator. DO NOT EDIT.
using System;
using System.Collections.Generic;
using Kreuzberg;
using Xunit;
using Kreuzberg.E2E;

namespace Kreuzberg.E2E.Ocr {
    public class OcrTests
    {
        [SkippableFact]
        public void OcrImageHelloWorld()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("images/test_hello_world.png");
            TestHelpers.SkipIfOfficeTestOnWindows("images/test_hello_world.png");
            var result = TestHelpers.RunExtraction("images/test_hello_world.png", "{\"force_ocr\":true,\"ocr\":{\"backend\":\"tesseract\",\"language\":\"eng\"}}");
            TestHelpers.AssertExpectedMime(result, new[] { "image/png" });
            TestHelpers.AssertMinContentLength(result, 5);
            TestHelpers.AssertContentContainsAny(result, new[] { "hello", "world" });
        }

        [SkippableFact]
        public void OcrImageNoText()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("images/flower_no_text.jpg");
            TestHelpers.SkipIfOfficeTestOnWindows("images/flower_no_text.jpg");
            var result = TestHelpers.RunExtraction("images/flower_no_text.jpg", "{\"force_ocr\":true,\"ocr\":{\"backend\":\"tesseract\",\"language\":\"eng\"}}");
            TestHelpers.AssertExpectedMime(result, new[] { "image/jpeg" });
            TestHelpers.AssertMaxContentLength(result, 200);
        }

        [SkippableFact]
        public void OcrPdfImageOnlyGerman()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdfs/image_only_german_pdf.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdfs/image_only_german_pdf.pdf");
            var result = TestHelpers.RunExtraction("pdfs/image_only_german_pdf.pdf", "{\"force_ocr\":true,\"ocr\":{\"backend\":\"tesseract\",\"language\":\"eng\"}}");
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 20);
            var metadataNode = TestHelpers.MetadataToJson(result.Metadata);
            TestHelpers.AssertMetadata(metadataNode, "format_type", @"{""eq"": ""pdf""}");
        }

        [SkippableFact]
        public void OcrPdfRotated90()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdfs/ocr_test_rotated_90.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdfs/ocr_test_rotated_90.pdf");
            var result = TestHelpers.RunExtraction("pdfs/ocr_test_rotated_90.pdf", "{\"force_ocr\":true,\"ocr\":{\"backend\":\"tesseract\",\"language\":\"eng\"}}");
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 10);
        }

        [SkippableFact]
        public void OcrPdfTesseract()
        {
            TestHelpers.SkipIfLegacyOfficeDisabled("pdfs/ocr_test.pdf");
            TestHelpers.SkipIfOfficeTestOnWindows("pdfs/ocr_test.pdf");
            var result = TestHelpers.RunExtraction("pdfs/ocr_test.pdf", "{\"force_ocr\":true,\"ocr\":{\"backend\":\"tesseract\",\"language\":\"eng\"}}");
            TestHelpers.AssertExpectedMime(result, new[] { "application/pdf" });
            TestHelpers.AssertMinContentLength(result, 20);
            TestHelpers.AssertContentContainsAny(result, new[] { "Docling", "Markdown", "JSON" });
        }

    }
}
