# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_kreuzberg_wrappers", use_symbols = TRUE, package_name = "kreuzberg")

#' @docType package
#' @usage NULL
#' @useDynLib kreuzberg, .registration = TRUE
NULL
