/* Code generated by kreuzberg-e2e-generator. DO NOT EDIT. */
/* Category: image */

#include "helpers.h"
#include <stdio.h>

static void test_image_image_metadata_only(void) {
    CExtractionResult *result = run_extraction("images/example.jpg", "{\"ocr\":null}");
    if (!result) return; /* skipped */
    assert_expected_mime(result, (const char *[]){"image/jpeg"}, 1);
    assert_max_content_length(result, 100);
    kreuzberg_free_result(result);
}

static void test_image_image_svg_basic(void) {
    CExtractionResult *result = run_extraction("xml/simple_svg.svg", NULL);
    if (!result) return; /* skipped */
    assert_expected_mime(result, (const char *[]){"image/svg+xml"}, 1);
    assert_min_content_length(result, 5);
    kreuzberg_free_result(result);
}

int main(void) {
    test_image_image_metadata_only();
    test_image_image_svg_basic();
    printf("test_image: all tests passed\n");
    return 0;
}
