/* Code generated by kreuzberg-e2e-generator. DO NOT EDIT. */
/* Category: structured */

#include "helpers.h"
#include <stdio.h>

static void test_structured_structured_csv_basic(void) {
    CExtractionResult *result = run_extraction("csv/stanley_cups.csv", NULL);
    if (!result) return; /* skipped */
    assert_expected_mime(result, (const char *[]){"text/csv"}, 1);
    assert_min_content_length(result, 20);
    kreuzberg_free_result(result);
}

static void test_structured_structured_json_basic(void) {
    CExtractionResult *result = run_extraction("json/sample_document.json", NULL);
    if (!result) return; /* skipped */
    assert_expected_mime(result, (const char *[]){"application/json"}, 1);
    assert_min_content_length(result, 20);
    assert_content_contains_any(result, (const char *[]){"Sample Document", "Test Author"}, 2);
    kreuzberg_free_result(result);
}

static void test_structured_structured_json_simple(void) {
    CExtractionResult *result = run_extraction("json/simple.json", NULL);
    if (!result) return; /* skipped */
    assert_expected_mime(result, (const char *[]){"application/json"}, 1);
    assert_min_content_length(result, 10);
    assert_content_contains_any(result, (const char *[]){"{", "name"}, 2);
    kreuzberg_free_result(result);
}

static void test_structured_structured_toml_basic(void) {
    CExtractionResult *result = run_extraction("data_formats/cargo.toml", NULL);
    if (!result) return; /* skipped */
    assert_expected_mime(result, (const char *[]){"application/toml", "text/toml"}, 2);
    assert_min_content_length(result, 10);
    kreuzberg_free_result(result);
}

static void test_structured_structured_yaml_basic(void) {
    CExtractionResult *result = run_extraction("yaml/simple.yaml", NULL);
    if (!result) return; /* skipped */
    assert_expected_mime(result, (const char *[]){"application/yaml", "text/yaml", "text/x-yaml", "application/x-yaml"}, 4);
    assert_min_content_length(result, 10);
    kreuzberg_free_result(result);
}

static void test_structured_structured_yaml_simple(void) {
    CExtractionResult *result = run_extraction("yaml/simple.yaml", NULL);
    if (!result) return; /* skipped */
    assert_expected_mime(result, (const char *[]){"application/x-yaml"}, 1);
    assert_min_content_length(result, 10);
    kreuzberg_free_result(result);
}

int main(void) {
    test_structured_structured_csv_basic();
    test_structured_structured_json_basic();
    test_structured_structured_json_simple();
    test_structured_structured_toml_basic();
    test_structured_structured_yaml_basic();
    test_structured_structured_yaml_simple();
    printf("test_structured: all tests passed\n");
    return 0;
}
