version: "3"

tasks:
  all:
    desc: Build all bindings across all languages
    cmds:
      - task: rust:build
      - task: rust:ffi:build
      - task: python:build
      - task: node:build
      - task: go:build
      - task: java:build
      - task: csharp:build
      - task: wasm:build
      - task: ruby:build
      - task: php:build
      - task: elixir:build
      - task: r:build
      - task: c:build

  all:dev:
    desc: Build all bindings in debug mode
    cmds:
      - task: rust:build:dev
      - task: rust:ffi:build:dev
      - task: python:build:dev
      - task: node:build:dev
      - task: go:build:dev
      - task: java:build:dev
      - task: csharp:build:dev
      - task: wasm:build:dev
      - task: ruby:build:dev
      - task: php:build:dev
      - task: elixir:build:dev
      - task: r:build:dev
      - task: c:build:dev

  all:release:
    desc: Build all bindings in release mode (optimized)
    cmds:
      - task: rust:build:release
      - task: rust:ffi:build:release
      - task: python:build:release
      - task: node:build:release
      - task: go:build:release
      - task: java:build:release
      - task: csharp:build:release
      - task: wasm:build:release
      - task: ruby:build:release
      - task: php:build:release
      - task: elixir:build:release
      - task: r:build:release
      - task: c:build:release

  all:ci:
    desc: Build all bindings in CI mode
    cmds:
      - task: rust:build:ci
      - task: rust:ffi:build:ci
      - task: python:build:ci
      - task: node:build:ci
      - task: go:build:ci
      - task: java:build:ci
      - task: csharp:build:ci
      - task: wasm:build:ci
      - task: ruby:build:ci
      - task: php:build:ci
      - task: elixir:build:ci
      - task: r:build:ci
      - task: c:build:ci

  cli-only:
    desc: Build Rust CLI only
    cmds:
      - task: rust:cli:build

  cli-only:dev:
    desc: Build Rust CLI in debug mode
    cmds:
      - task: rust:cli:build:dev

  cli-only:release:
    desc: Build Rust CLI in release mode
    cmds:
      - task: rust:cli:build:release

  ffi-only:
    desc: Build Rust FFI library only
    cmds:
      - task: rust:ffi:build

  ffi-only:dev:
    desc: Build Rust FFI in debug mode
    cmds:
      - task: rust:ffi:build:dev

  ffi-only:release:
    desc: Build Rust FFI in release mode
    cmds:
      - task: rust:ffi:build:release

  core:
    desc: Build core Rust and FFI (foundation for C bindings)
    cmds:
      - task: rust:build
      - task: rust:ffi:build

  core:dev:
    desc: Build core Rust and FFI in debug mode
    cmds:
      - task: rust:build:dev
      - task: rust:ffi:build:dev

  core:release:
    desc: Build core Rust and FFI in release mode
    cmds:
      - task: rust:build:release
      - task: rust:ffi:build:release

  jvm-bindings:
    desc: Build JVM-dependent bindings (Java, C#, Ruby, PHP)
    cmds:
      - task: rust:ffi:build
      - task: java:build
      - task: csharp:build
      - task: ruby:build
      - task: php:build

  jvm-bindings:dev:
    desc: Build JVM bindings in debug mode
    cmds:
      - task: rust:ffi:build:dev
      - task: java:build:dev
      - task: csharp:build:dev
      - task: ruby:build:dev
      - task: php:build:dev

  jvm-bindings:release:
    desc: Build JVM bindings in release mode
    cmds:
      - task: rust:ffi:build:release
      - task: java:build:release
      - task: csharp:build:release
      - task: ruby:build:release
      - task: php:build:release

  js-ecosystem:
    desc: Build JavaScript ecosystem bindings (Node.js, WASM)
    cmds:
      - task: node:build
      - task: wasm:build

  js-ecosystem:dev:
    desc: Build JS ecosystem in debug mode
    cmds:
      - task: node:build:dev
      - task: wasm:build:dev

  js-ecosystem:release:
    desc: Build JS ecosystem in release mode
    cmds:
      - task: node:build:release
      - task: wasm:build:release

  datascience:
    desc: Build data science bindings (Python + Rust)
    cmds:
      - task: rust:build
      - task: python:build

  datascience:dev:
    desc: Build data science stack in debug mode
    cmds:
      - task: rust:build:dev
      - task: python:build:dev

  datascience:release:
    desc: Build data science stack in release mode
    cmds:
      - task: rust:build:release
      - task: python:build:release

  systems:
    desc: Build systems languages (Rust, Go, C#, C)
    cmds:
      - task: rust:build
      - task: rust:ffi:build
      - task: go:build
      - task: csharp:build
      - task: c:build

  systems:dev:
    desc: Build systems languages in debug mode
    cmds:
      - task: rust:build:dev
      - task: rust:ffi:build:dev
      - task: go:build:dev
      - task: csharp:build:dev
      - task: c:build:dev

  systems:release:
    desc: Build systems languages in release mode
    cmds:
      - task: rust:build:release
      - task: rust:ffi:build:release
      - task: go:build:release
      - task: csharp:build:release
      - task: c:build:release

  web:
    desc: Build web-focused bindings (Node.js, WASM, Python)
    cmds:
      - task: node:build
      - task: wasm:build
      - task: python:build

  web:dev:
    desc: Build web stack in debug mode
    cmds:
      - task: node:build:dev
      - task: wasm:build:dev
      - task: python:build:dev

  web:release:
    desc: Build web stack in release mode
    cmds:
      - task: node:build:release
      - task: wasm:build:release
      - task: python:build:release
