// Code generated by kreuzberg-e2e-generator. DO NOT EDIT.
// Category: image

package e2e

import "testing"

func TestImageImageMetadataOnly(t *testing.T) {
	result := runExtraction(t, "images/example.jpg", []byte(`{
"ocr": null
}`))
	assertExpectedMime(t, result, []string{"image/jpeg"})
	assertMaxContentLength(t, result, 100)
}

func TestImageImageSvgBasic(t *testing.T) {
	result := runExtraction(t, "xml/simple_svg.svg", nil)
	assertExpectedMime(t, result, []string{"image/svg+xml"})
	assertMinContentLength(t, result, 5)
}
