// Code generated by kreuzberg-e2e-generator. DO NOT EDIT.
// Category: pdf

package e2e

import (
	"os"
	"sync"
	"testing"
)

// pdfiumOnce ensures Pdfium is initialized only once across all PDF tests
var pdfiumOnce sync.Once

// init() runs before any tests in this file and initializes Pdfium
func init() {
	// Initialize Pdfium early to avoid "already initialized" errors
	_ = initializePdfium()
}

// TestMain is called before all tests in this file run.
func TestMain(m *testing.M) {
	// Initialize Pdfium by doing a dummy extraction
	_ = initializePdfium()

	// Run all tests
	code := m.Run()
	os.Exit(code)
}

// initializePdfium triggers Pdfium initialization by performing a simple extraction
func initializePdfium() error {
	var err error
	pdfiumOnce.Do(func() {
		// Create a minimal PDF to initialize the library
		defer func() {
			if r := recover(); r != nil {
				// If initialization fails, we'll handle it in individual tests
				err = nil
			}
		}()
		_ = runExtraction(&testing.T{}, "pdfs/fake_memo.pdf", nil)
	})
	return err
}

func TestPdfPdfAssemblyTechnical(t *testing.T) {
	result := runExtraction(t, "pdfs/assembly_language_for_beginners_al4_b_en.pdf", nil)
	assertExpectedMime(t, result, []string{"application/pdf"})
	assertMinContentLength(t, result, 5000)
	assertContentContainsAny(t, result, []string{"assembly", "register", "instruction"})
}

func TestPdfPdfBayesianDataAnalysis(t *testing.T) {
	result := runExtraction(t, "pdfs/bayesian_data_analysis_third_edition_13th_feb_2020.pdf", nil)
	assertExpectedMime(t, result, []string{"application/pdf"})
	assertMinContentLength(t, result, 10000)
	assertContentContainsAny(t, result, []string{"Bayesian", "probability", "distribution"})
}

func TestPdfPdfCodeAndFormula(t *testing.T) {
	result := runExtraction(t, "pdfs/code_and_formula.pdf", nil)
	assertExpectedMime(t, result, []string{"application/pdf"})
	assertMinContentLength(t, result, 100)
}

func TestPdfPdfDeepLearning(t *testing.T) {
	result := runExtraction(t, "pdfs/fundamentals_of_deep_learning_2014.pdf", nil)
	assertExpectedMime(t, result, []string{"application/pdf"})
	assertMinContentLength(t, result, 1000)
	assertContentContainsAny(t, result, []string{"neural", "network", "deep learning"})
}

func TestPdfPdfEmbeddedImages(t *testing.T) {
	result := runExtraction(t, "pdfs/embedded_images_tables.pdf", nil)
	assertExpectedMime(t, result, []string{"application/pdf"})
	assertMinContentLength(t, result, 50)
	assertTableCount(t, result, intPtr(0), nil)
}

func TestPdfPdfGoogleDoc(t *testing.T) {
	result := runExtraction(t, "pdfs/google_doc_document.pdf", nil)
	assertExpectedMime(t, result, []string{"application/pdf"})
	assertMinContentLength(t, result, 50)
}

func TestPdfPdfLargeCiml(t *testing.T) {
	result := runExtraction(t, "pdfs/a_course_in_machine_learning_ciml_v0_9_all.pdf", nil)
	assertExpectedMime(t, result, []string{"application/pdf"})
	assertMinContentLength(t, result, 10000)
	assertContentContainsAny(t, result, []string{"machine learning", "algorithm", "training"})
}

func TestPdfPdfNonEnglishGerman(t *testing.T) {
	result := runExtraction(t, "pdfs/5_level_paging_and_5_level_ept_intel_revision_1_1_may_2017.pdf", nil)
	assertExpectedMime(t, result, []string{"application/pdf"})
	assertMinContentLength(t, result, 100)
	assertContentContainsAny(t, result, []string{"Intel", "paging"})
}

func TestPdfPdfRightToLeft(t *testing.T) {
	result := runExtraction(t, "pdfs/right_to_left_01.pdf", nil)
	assertExpectedMime(t, result, []string{"application/pdf"})
	assertMinContentLength(t, result, 50)
}

func TestPdfPdfSimpleText(t *testing.T) {
	result := runExtraction(t, "pdfs/fake_memo.pdf", nil)
	assertExpectedMime(t, result, []string{"application/pdf"})
	assertMinContentLength(t, result, 50)
	assertContentContainsAny(t, result, []string{"May 5, 2023", "To Whom it May Concern", "Mallori"})
}

func TestPdfPdfTablesLarge(t *testing.T) {
	result := runExtraction(t, "pdfs_with_tables/large.pdf", nil)
	assertExpectedMime(t, result, []string{"application/pdf"})
	assertMinContentLength(t, result, 500)
	assertTableCount(t, result, intPtr(1), nil)
}

func TestPdfPdfTablesMedium(t *testing.T) {
	result := runExtraction(t, "pdfs_with_tables/medium.pdf", nil)
	assertExpectedMime(t, result, []string{"application/pdf"})
	assertMinContentLength(t, result, 100)
	assertTableCount(t, result, intPtr(1), nil)
}

func TestPdfPdfTablesSmall(t *testing.T) {
	result := runExtraction(t, "pdfs_with_tables/tiny.pdf", nil)
	assertExpectedMime(t, result, []string{"application/pdf"})
	assertMinContentLength(t, result, 50)
	assertContentContainsAll(t, result, []string{"Table 1", "Selected Numbers", "Celsius", "Fahrenheit", "Water Freezing Point", "Water Boiling Point"})
	assertTableCount(t, result, intPtr(1), nil)
}

func TestPdfPdfTechnicalStatLearning(t *testing.T) {
	result := runExtraction(t, "pdfs/an_introduction_to_statistical_learning_with_applications_in_r_islr_sixth_printing.pdf", nil)
	assertExpectedMime(t, result, []string{"application/pdf"})
	assertMinContentLength(t, result, 10000)
	assertContentContainsAny(t, result, []string{"statistical", "regression", "learning"})
}
