name: Setup Maven 3.9.11
description: Install Maven 3.9.11 in a cross-platform way
runs:
  using: composite
  steps:
    - name: Setup Maven 3.9.11
      shell: bash
      run: |
        MAVEN_VERSION="3.9.11"
        MAVEN_PRIMARY_URL="https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/${MAVEN_VERSION}/apache-maven-${MAVEN_VERSION}-bin.tar.gz"
        MAVEN_FALLBACK_URL="https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz"

        # Use a temp directory that works across platforms
        TEMP_DIR="$(pwd)/maven-temp"
        mkdir -p "$TEMP_DIR"

        if ! curl -fsSL --retry 3 --retry-all-errors --retry-delay 5 \
          "$MAVEN_PRIMARY_URL" -o "$TEMP_DIR/maven.tar.gz"; then
          echo "Primary Maven URL failed, falling back to archive.apache.org"
          curl -fsSL --retry 3 --retry-all-errors --retry-delay 5 \
            "$MAVEN_FALLBACK_URL" -o "$TEMP_DIR/maven.tar.gz"
        fi
        tar -xzf "$TEMP_DIR/maven.tar.gz" -C "$TEMP_DIR"

        MAVEN_HOME="$TEMP_DIR/apache-maven-${MAVEN_VERSION}"
        echo "$MAVEN_HOME/bin" >> "$GITHUB_PATH"

        # Verify Maven version
        "$MAVEN_HOME/bin/mvn" --version
